//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrickBreaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrickBreaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;level&gt;
        ///	&lt;block&gt;
        ///		&lt;x&gt;59&lt;/x&gt;
        ///		&lt;y&gt;37&lt;/y&gt;
        ///		&lt;hp&gt;8&lt;/hp&gt;
        ///		&lt;colour&gt;DarkBlue&lt;/colour&gt;
        ///	&lt;/block&gt;
        ///	&lt;block&gt;
        ///		&lt;x&gt;171&lt;/x&gt;
        ///		&lt;y&gt;12&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;colour&gt;Black&lt;/colour&gt;
        ///	&lt;/block&gt;
        ///	&lt;block&gt;
        ///		&lt;x&gt;171&lt;/x&gt;
        ///		&lt;y&gt;53&lt;/y&gt;
        ///		&lt;hp&gt;5&lt;/hp&gt;
        ///		&lt;colour&gt;DarkRed&lt;/colour&gt;
        ///	&lt;/block&gt;
        ///	&lt;block&gt;
        ///		&lt;x&gt;171&lt;/x&gt;
        ///		&lt;y&gt;84&lt;/y&gt;
        ///		&lt;hp&gt;5&lt;/hp&gt;
        ///		&lt;colour&gt;DarkRed&lt;/colour&gt;
        ///	&lt;/block&gt;
        ///	&lt;block&gt;
        ///		&lt;x&gt;171&lt;/x&gt;
        ///		&lt;y&gt;115&lt;/y&gt;
        ///		&lt;hp&gt;5&lt;/hp&gt;
        ///		&lt;colour&gt;DarkRed&lt;/colour&gt;
        ///	&lt;/block&gt;
        ///	&lt;block&gt;
        ///		&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level07 {
            get {
                return ResourceManager.GetString("level07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;level&gt;
        ///	&lt;block&gt;
        ///		&lt;x&gt;95&lt;/x&gt;
        ///		&lt;y&gt;68&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;colour&gt;DarkRed&lt;/colour&gt;
        ///	&lt;/block&gt;
        ///	&lt;block&gt;
        ///		&lt;x&gt;160&lt;/x&gt;
        ///		&lt;y&gt;135&lt;/y&gt;
        ///		&lt;hp&gt;3&lt;/hp&gt;
        ///		&lt;colour&gt;YellowGreen&lt;/colour&gt;
        ///	&lt;/block&gt;
        ///	&lt;block&gt;
        ///		&lt;x&gt;277&lt;/x&gt;
        ///		&lt;y&gt;69&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;colour&gt;DarkRed&lt;/colour&gt;
        ///	&lt;/block&gt;
        ///	&lt;block&gt;
        ///		&lt;x&gt;340&lt;/x&gt;
        ///		&lt;y&gt;167&lt;/y&gt;
        ///		&lt;hp&gt;2&lt;/hp&gt;
        ///		&lt;colour&gt;Goldenrod&lt;/colour&gt;
        ///	&lt;/block&gt;
        ///	&lt;block&gt;
        ///		&lt;x&gt;420&lt;/x&gt;
        ///		&lt;y&gt;69&lt;/y&gt;
        ///		&lt;hp&gt;2&lt;/hp&gt;
        ///		&lt;colour&gt;Goldenrod&lt;/colour&gt;
        ///	&lt;/block&gt;
        ///	&lt;b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level1 {
            get {
                return ResourceManager.GetString("level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Level1_Background {
            get {
                object obj = ResourceManager.GetObject("Level1_Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Level2_Background {
            get {
                object obj = ResourceManager.GetObject("Level2_Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Level3_Background {
            get {
                object obj = ResourceManager.GetObject("Level3_Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Level4_Background {
            get {
                object obj = ResourceManager.GetObject("Level4_Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Level5_Background {
            get {
                object obj = ResourceManager.GetObject("Level5_Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Level6_Background {
            get {
                object obj = ResourceManager.GetObject("Level6_Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Level7_Background {
            get {
                object obj = ResourceManager.GetObject("Level7_Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Level8_Background {
            get {
                object obj = ResourceManager.GetObject("Level8_Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LoseScreen_Background {
            get {
                object obj = ResourceManager.GetObject("LoseScreen_Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Menu_Background {
            get {
                object obj = ResourceManager.GetObject("Menu_Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VictoryScreen_Background {
            get {
                object obj = ResourceManager.GetObject("VictoryScreen_Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
